// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        pgtype.UUID        `db:"id"`
	Name      string             `db:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
}

type Program struct {
	ID          pgtype.UUID        `db:"id"`
	Title       string             `db:"title"`
	Description pgtype.Text        `db:"description"`
	CategoryID  pgtype.UUID        `db:"category_id"`
	Language    pgtype.Text        `db:"language"`
	Duration    pgtype.Int4        `db:"duration"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `db:"id"`
	Email        string             `db:"email"`
	PasswordHash string             `db:"password_hash"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
}
