// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCategory(ctx context.Context, name string) (CreateCategoryRow, error)
	CreateProgram(ctx context.Context, arg CreateProgramParams) (CreateProgramRow, error)
	DeleteProgram(ctx context.Context, id pgtype.UUID) error
	GetCategories(ctx context.Context) ([]GetCategoriesRow, error)
	GetProgram(ctx context.Context, id pgtype.UUID) (GetProgramRow, error)
	GetProgramsByCategory(ctx context.Context, id pgtype.UUID) ([]GetProgramsByCategoryRow, error)
	ListPrograms(ctx context.Context) ([]ListProgramsRow, error)
	SearchPrograms(ctx context.Context, dollar_1 pgtype.Text) ([]SearchProgramsRow, error)
	UpdateProgram(ctx context.Context, arg UpdateProgramParams) (UpdateProgramRow, error)
}

var _ Querier = (*Queries)(nil)
