// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package database

import (
	"context"
)

const dummy = `-- name: Dummy :one
SELECT 1
`

func (q *Queries) Dummy(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, dummy)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
